# Generated by Django 6.1 on 2026-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_access_private',
            field=models.BooleanField(default=False),
        ),
    ]
