# Generated by Django 6.1 on 2026-09-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_profile_can_access_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_access_private',
            new_name='can_manage_private',
        ),
    ]
